version: 1
build:
  binary: meowd
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 10100000000000000000000000ameow
  mnemonic: dentist tomato kick join sure exit bamboo actor mean million embark insane faint beauty mass marble husband jealous biology clay shell theory craft shrimp
- name: bob
  coins:
  - 5000000000000ameow
  mnemonic: remain switch sentence try famous wonder column jazz artist slender vacant stay beach leg fatigue fly enhance wage member shell verify pepper still begin
faucet:
  name: bob
  coins:
  - 10ameow
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: ameow
    evm:
      params:
        evm_denom: ameow
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: ameow
      voting_params:
        voting_period: 120s
    inflation:
      params:
        mint_denom: ameow
    mint:
      params:
        mint_denom: ameow
    staking:
      params:
        bond_denom: ameow
  chain_id: meow_6666-1
validators:
- name: alice
  bonded: 100000000000000000000000ameow
  app:
    api:
      swagger: true
    evm-rpc:
      address: 0.0.0.0:8545
      ws-address: 0.0.0.0:8546
    grpc-web:
      enable: true
    json-rpc:
      api: eth,txpool,personal,net,debug,web3
    rpc:
      cors_allowed_origins:
      - '*'
  config:
    cors_allowed_origins:
    - '*'
  client:
    broadcast-mode: sync
    chain-id: meow_6666-1
    keyring-backend: test
    node: tcp://localhost:26657
    output: text
  home: $HOME/.meow
