version: '3'

services:
  meownode0:
    container_name: meownode0
    image: "meow/node:latest"
    ports:
      - "26656-26657:26656-26657"
      - "8545-8546:8545-8546"
      - "1317:1317"
    volumes:
      - ./build/meownode0/:/opt/build/meow_home/
    command: bash ${COMMAND}.sh meownode0
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  meownode1:
    container_name: meownode1
    image: "meow/node:latest"
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - ./build/meownode1/:/opt/build/meow_home/
    command: bash ${COMMAND}.sh meownode1
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  meownode2:
    container_name: meownode2
    image: "meow/node:latest"
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build/meownode2/:/opt/build/meow_home/
    command: bash ${COMMAND}.sh meownode2
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  meownode3:
    container_name: meownode3
    image: "meow/node:latest"
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build/meownode3/:/opt/build/meow_home/
    command: bash ${COMMAND}.sh meownode3
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.167.10.0/16